from enum import IntEnum


class AnimationType(IntEnum):
    HK_UNKNOWN_ANIMATION = 0
    HK_INTERLEAVED_ANIMATION = 1
    HK_DELTA_COMPRESSED_ANIMATION = 2
    HK_WAVELET_COMPRESSED_ANIMATION = 3
    HK_MIRRORED_ANIMATION = 4
    HK_SPLINE_COMPRESSED_ANIMATION = 5
    HK_QUANTIZED_COMPRESSED_ANIMATION = 6


class BlendHint(IntEnum):
    NORMAL = 0
    ADDITIVE = 1


class DataType(IntEnum):
    HKX_DT_NONE = 0
    HKX_DT_UINT8 = 1
    HKX_DT_INT16 = 2
    HKX_DT_UINT32 = 3
    HKX_DT_FLOAT = 4


class IndexType(IntEnum):
    INDEX_TYPE_INVALID = 0
    INDEX_TYPE_TRI_LIST = 1
    INDEX_TYPE_TRI_STRIP = 2
    INDEX_TYPE_TRI_FAN = 3
    INDEX_TYPE_MAX_ID = 4


class TextureType(IntEnum):
    TEX_UNKNOWN = 0
    TEX_DIFFUSE = 1
    TEX_REFLECTION = 2
    TEX_BUMP = 3
    TEX_NORMAL = 4
    TEX_DISPLACEMENT = 5
    TEX_SPECULAR = 6
    TEX_SPECULARANDGLOSS = 7
    TEX_OPACITY = 8
    TEX_EMISSIVE = 9
    TEX_REFRACTION = 10
    TEX_GLOSS = 11
    TEX_NOTEXPORTED = 12


class Hint(IntEnum):
    HINT_NONE = 0
    HINT_IGNORE = 1
    HINT_TRANSFORM = 2
    HINT_SCALE = 4
    HINT_TRANSFORM_AND_SCALE = 6
    HINT_FLIP = 8


class RayHitType(IntEnum):
    HIT_CAP0 = 0
    HIT_CAP1 = 1
    HIT_BODY = 2


class WeldResult(IntEnum):
    WELD_RESULT_REJECT_CONTACT_POINT = 0
    WELD_RESULT_ACCEPT_CONTACT_POINT_MODIFIED = 1
    WELD_RESULT_ACCEPT_CONTACT_POINT_UNMODIFIED = 2


class SpuCollisionCallbackEventFilter(IntEnum):
    SPU_SEND_NONE = 0
    SPU_SEND_CONTACT_POINT_ADDED = 1
    SPU_SEND_CONTACT_POINT_PROCESS = 2
    SPU_SEND_CONTACT_POINT_REMOVED = 4
    SPU_SEND_CONTACT_POINT_ADDED_OR_PROCESS = 3


class MtChecks(IntEnum):
    MULTI_THREADING_CHECKS_ENABLE = 0
    MULTI_THREADING_CHECKS_IGNORE = 1


class ForceCollideOntoPpuReasons(IntEnum):
    FORCE_PPU_USER_REQUEST = 1
    FORCE_PPU_SHAPE_REQUEST = 2
    FORCE_PPU_MODIFIER_REQUEST = 4
    FORCE_PPU_SHAPE_UNCHECKED = 8


class AccessType(IntEnum):
    HK_ACCESS_IGNORE = 0
    HK_ACCESS_RO = 1
    HK_ACCESS_RW = 2


class ResponseType(IntEnum):
    RESPONSE_INVALID = 0
    RESPONSE_SIMPLE_CONTACT = 1
    RESPONSE_REPORTING = 2
    RESPONSE_NONE = 3
    RESPONSE_MAX_ID = 4


class ConstraintPriority(IntEnum):
    PRIORITY_INVALID = 0
    PRIORITY_PSI = 1
    PRIORITY_SIMPLIFIED_TOI_UNUSED = 2
    PRIORITY_TOI = 3
    PRIORITY_TOI_HIGHER = 4
    PRIORITY_TOI_FORCED = 5
    NUM_PRIORITIES = 6


class ConstraintType(IntEnum):
    CONSTRAINT_TYPE_BALLANDSOCKET = 0
    CONSTRAINT_TYPE_HINGE = 1
    CONSTRAINT_TYPE_LIMITEDHINGE = 2
    CONSTRAINT_TYPE_POINTTOPATH = 3
    CONSTRAINT_TYPE_PRISMATIC = 6
    CONSTRAINT_TYPE_RAGDOLL = 7
    CONSTRAINT_TYPE_STIFFSPRING = 8
    CONSTRAINT_TYPE_WHEEL = 9
    CONSTRAINT_TYPE_GENERIC = 10
    CONSTRAINT_TYPE_CONTACT = 11
    CONSTRAINT_TYPE_BREAKABLE = 12
    CONSTRAINT_TYPE_MALLEABLE = 13
    CONSTRAINT_TYPE_POINTTOPLANE = 14
    CONSTRAINT_TYPE_PULLEY = 15
    CONSTRAINT_TYPE_ROTATIONAL = 16
    CONSTRAINT_TYPE_HINGE_LIMITS = 18
    CONSTRAINT_TYPE_RAGDOLL_LIMITS = 19
    CONSTRAINT_TYPE_CUSTOM = 20
    CONSTRAINT_TYPE_RACK_AND_PINION = 21
    CONSTRAINT_TYPE_COG_WHEEL = 22
    BEGIN_CONSTRAINT_CHAIN_TYPES = 100
    CONSTRAINT_TYPE_STIFF_SPRING_CHAIN = 100
    CONSTRAINT_TYPE_BALL_SOCKET_CHAIN = 101
    CONSTRAINT_TYPE_POWERED_CHAIN = 102


class AtomType(IntEnum):
    TYPE_INVALID = 0
    TYPE_BRIDGE = 1
    TYPE_SET_LOCAL_TRANSFORMS = 2
    TYPE_SET_LOCAL_TRANSLATIONS = 3
    TYPE_SET_LOCAL_ROTATIONS = 4
    TYPE_BALL_SOCKET = 5
    TYPE_STIFF_SPRING = 6
    TYPE_LIN = 7
    TYPE_LIN_SOFT = 8
    TYPE_LIN_LIMIT = 9
    TYPE_LIN_FRICTION = 10
    TYPE_LIN_MOTOR = 11
    TYPE_2D_ANG = 12
    TYPE_ANG = 13
    TYPE_ANG_LIMIT = 14
    TYPE_TWIST_LIMIT = 15
    TYPE_CONE_LIMIT = 16
    TYPE_ANG_FRICTION = 17
    TYPE_ANG_MOTOR = 18
    TYPE_RAGDOLL_MOTOR = 19
    TYPE_PULLEY = 20
    TYPE_RACK_AND_PINION = 21
    TYPE_COG_WHEEL = 22
    TYPE_SETUP_STABILIZATION = 23
    TYPE_OVERWRITE_PIVOT = 24
    TYPE_CONTACT = 25
    TYPE_MODIFIER_SOFT_CONTACT = 26
    TYPE_MODIFIER_MASS_CHANGER = 27
    TYPE_MODIFIER_VISCOUS_SURFACE = 28
    TYPE_MODIFIER_MOVING_SURFACE = 29
    TYPE_MODIFIER_IGNORE_CONSTRAINT = 30
    TYPE_MODIFIER_CENTER_OF_MASS_CHANGER = 31
    TYPE_MAX = 32


class MotionType(IntEnum):
    MOTION_INVALID = 0
    MOTION_DYNAMIC = 1
    MOTION_SPHERE_INERTIA = 2
    MOTION_BOX_INERTIA = 3
    MOTION_KEYFRAMED = 4
    MOTION_FIXED = 5
    MOTION_THIN_BOX_INERTIA = 6
    MOTION_CHARACTER = 7
    MOTION_MAX_ID = 8


class MotorIndex(IntEnum):
    MOTOR_TWIST = 0
    MOTOR_PLANE = 1
    MOTOR_CONE = 2


class Axis(IntEnum):
    AXIS_TWIST = 0
    AXIS_PLANES = 1
    AXIS_CROSS_PRODUCT = 2


class MotorType(IntEnum):
    TYPE_INVALID = 0
    TYPE_POSITION = 1
    TYPE_VELOCITY = 2
    TYPE_SPRING_DAMPER = 3
    TYPE_CALLBACK = 4
    TYPE_MAX = 5


class MeasurementMode(IntEnum):
    ZERO_WHEN_VECTORS_ALIGNED = 0
    ZERO_WHEN_VECTORS_PERPENDICULAR = 1


class SolverType(IntEnum):
    SOLVER_TYPE_INVALID = 0
    SOLVER_TYPE_2ITERS_SOFT = 1
    SOLVER_TYPE_2ITERS_MEDIUM = 2
    SOLVER_TYPE_2ITERS_HARD = 3
    SOLVER_TYPE_4ITERS_SOFT = 4
    SOLVER_TYPE_4ITERS_MEDIUM = 5
    SOLVER_TYPE_4ITERS_HARD = 6
    SOLVER_TYPE_8ITERS_SOFT = 7
    SOLVER_TYPE_8ITERS_MEDIUM = 8
    SOLVER_TYPE_8ITERS_HARD = 9
    SOLVER_TYPE_MAX_ID = 10


class hkpFilterType(IntEnum):
    HK_FILTER_UNKNOWN = 0
    HK_FILTER_NULL = 1
    HK_FILTER_GROUP = 2
    HK_FILTER_LIST = 3
    HK_FILTER_CUSTOM = 4
    HK_FILTER_PAIR = 5
    HK_FILTER_CONSTRAINT = 6


class ConvexListCollisionType(IntEnum):
    TREAT_CONVEX_LIST_AS_NORMAL = 0
    TREAT_CONVEX_LIST_AS_LIST = 1
    TREAT_CONVEX_LIST_AS_CONVEX = 2


class ConstraintSource(IntEnum):
    NO_CONSTRAINTS = 0
    REFERENCE_POSE = 1
    CURRENT_POSE = 2


class MappingType(IntEnum):
    HK_RAGDOLL_MAPPING = 0
    HK_RETARGETING_MAPPING = 1
